#!/usr/bin/ash

run_hook() {
	echo "Starting tailscale"

	modprobe tun
	while ! [ -e /dev/net/tun ]; do
		sleep 1
	done

	(
		[ -r /etc/tailscale/tailscaled.conf ] && . /etc/tailscale/tailscaled.conf
		tailscaled -state "/etc/tailscale/tailscaled.state" -port "${tailscale_port:-41641}" $tailscaled_args &
		tailscale up --timeout="${tailscale_timeout:-20s}" $tailscale_args
	)
}

run_cleanuphook() {
	killall tailscaled
}

# vim: ft=sh noexpandtab
